buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.76.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'baseline-error-prone-root'

include 'baseline-error-prone'
include 'baseline-null-away'
include 'gradle-baseline-error-prone'
