apply plugin: 'java-library'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.external-publish-gradle-plugin'
apply plugin: 'com.palantir.gradle-plugin-testing'

dependencies {
    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'
    implementation gradleApi()
    implementation 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone'
    implementation 'net.ltgt.gradle:gradle-errorprone-plugin'
    implementation 'com.google.guava:guava'

    testImplementation 'com.palantir.gradle.plugintesting:gradle-plugin-testing-junit'
    gradlePluginForTesting 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin'
}

// Baseline errorprone needs to give jars to the compilation process to enable testing, so we publish to maven
// local first then they are available to the test process.
tasks.test.dependsOn ':baseline-error-prone:publishToMavenLocal'
tasks.test.dependsOn ':baseline-null-away:publishToMavenLocal'
tasks.test.dependsOn tasks.named('publishToMavenLocal')

// Incorrectly identifies tests as jqwuik usage
tasks.checkJUnitDependencies.enabled = false

tasks.withType(JavaCompile) {
    options.errorprone {
        disable('StrictUnusedVariable')
    }
}

test {
    environment 'CIRCLE_ARTIFACTS', "${buildDir}/artifacts"
    environment 'CIRCLE_TEST_REPORTS', "${buildDir}/circle-reports"

    // This sets the baselineErrorProneGradle property so that the tests know which version of baseline-error-prone
    // to request from mavenLocal()
    environment 'ORG_GRADLE_PROJECT_baselineErrorProneVersion', project.version

    systemProperty 'ignoreDeprecations', 'true'
}

gradlePlugin {
    website = 'https://github.com/palantir/baseline-error-prone'
    vcsUrl = 'https://github.com/palantir/baseline-error-prone'

    plugins {
        baselineErrorProneRootPlugin {
            id = 'com.palantir.baseline-error-prone-root'
            displayName = 'Palantir Baseline Error Prone Root Plugin'
            implementationClass = 'com.palantir.gradle.baselineerrorprone.BaselineErrorProneRoot'
            description = 'Applies `com.palantir.baseline-error-prone` to all projects'
            tags.set(['java', 'checkstyle', 'code quality'])
        }
        baselineErrorPronePlugin {
            id = 'com.palantir.baseline-error-prone'
            displayName = 'Palantir Baseline Error Prone Plugin'
            implementationClass = 'com.palantir.gradle.baselineerrorprone.BaselineErrorProne'
            description = 'Baseline Java is a collection of Gradle plugins for configuring code quality tools in builds.'
            tags.set(['java', 'checkstyle', 'code quality'])
        }
        baselineNullAwayPlugin {
            id = 'com.palantir.baseline-null-away'
            displayName = 'Palantir Baseline NullAway Plugin'
            implementationClass = 'com.palantir.gradle.baselineerrorprone.BaselineNullAway'
            description = 'Configures NullAway for Palantir use.'
            tags.set(['java', 'checkstyle', 'code quality'])
        }
    }
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
}

